name: unittesting

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Testing code
        shell: bash
        run: |
          pytest treeTest.py
        