name: testing

on:
  pull_request:
    branches:
      - main

jobs:
  run:
    name: Unittesting
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install pytest

      - name: 📥 Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 🚀 Run tests
        shell: bash
        run: |
          pytest treeTest.py



# name: unittesting

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install pytest

#       - name: Testing code
#         shell: bash
#         run: |
#           find treeTest.py
        