name: Generate documentation

on:
  label:
    types:
      - created 
    tags:
      - v**     
jobs:
  run:
    name: Unittesting
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install doxygen

      - name: 📥 Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: run doxygen
        shell: bash
        run: |
          doxygen -g
          doxygen
        working-directory: .
      - name: Upload documentation
        uses: actions/upload-artifact@v3
        with:
          name: doxygen-docs
          path: docs/html
